version: "3"

includes:
  terraform: ./Taskfile_terraform.yml

tasks:
  setup:
    desc: sets up task[taskfile], local cluster, and other tools this repo uses
    ignore_error: true
    cmds:
      - brew install go-task # Task for takefile
      - brew install act
      - brew install gh
      - brew install kubectl
      - brew install podman
      - brew install argocd
      - brew install kind
      - podman machine init
      - podman machine start
      - kind create cluster --name k8s --wait 30s
      - export KIND_EXPERIMENTAL_PROVIDER=podman
      - kubectl config use-context kind-k8s
  start:
    aliases: [st]
    desc: stops running podman machine
    cmds:
      - podman machine start
      - kubectl config use-context kind-k8s
      - export KIND_EXPERIMENTAL_PROVIDER=podman
  stop:
    aliases: [sp]
    desc: stops running podman machine
    cmd: podman machine stop
  push:
    aliases: [p]
    desc: git add, commit, and push changes
    cmds:
      - git add -A
      - git commit -m "updates"
      - git push
