apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-script
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
        - name: hello
          image: busybox:1.36
          command: ["/bin/sh"]
          args: ["-c", "echo 'hello' && sleep 3600"]
