apiVersion: v1
kind: Namespace
metadata:
  name: prod
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-prod
  namespace: argocd
spec:
  project: default # default AppProject created by argo when first deployed
  source:
    repoURL: https://github.com/rithik-sandron/devops.git
    targetRevision: HEAD
    path: app
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
