name: "Composite Action"
description: "this is to study composite workflow"

inputs:
  repo-token:
    description: "Github PA Token"
    required: false
    default: ${{ github.token }}

  path:
    description: "Path to the shell script to run"
    required: true

outputs:
  result:
    description: "Result from init.sh"
    value: ${{ steps.script.outputs.result }}

runs:
  using: "composite"
  steps:
    - id: action-path
      run: echo "Action path= $GITHUB_ACTION_PATH"
      shell: bash

    - id: script
      name: Run Script
      shell: bash
      run: bash ${{ inputs.path }}
