name: "Composite Action"
description: "this is to study composite workflow"
inputs:
  repo-token:
    description: "Github PA Token"
    required: false
    default: ${{ github.token }}
outputs:
  ref:
    description: "Checked out ref"
    value: ${{ steps.checkout.outputs.ref }}
runs:
  using: "composite"
  steps:
    - name: Checkout Repo
      id: checkout
      uses: actions/checkout@v4

    - name: Run Script
      shell: bash
      run: ./github/actions/composite/init.sh
