name: CI

on:
  push:
    branches:
      - main
      - master

jobs:
  run-composite-action:
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout Repo
        uses: actions/checkout@v4

      - run: echo "Ref = $GITHUB_REF"
      - run: echo "Event = $GITHUB_EVENT_NAME"
      - run: echo "workspace path = $GITHUB_WORKSPACE"
      - run: echo "run by = $GITHUB_ACTOR"

      - id: ci
        uses: ./.github/actions/composite
        with:
          path: $GITHUB_WORKSPACE/init.sh