name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Ref = $GITHUB_REF"
      - run: echo "Event = $GITHUB_EVENT_NAME"
      - run: echo "workspace path = $GITHUB_WORKSPACE"
      - run: echo "run by = $GITHUB_ACTOR"

      - uses: actions/checkout@v4

      - id: build
        uses: ./.github/actions/composite/build
        with:
          dockerfile: $GITHUB_WORKSPACE/app/Dockerfile
          path: $GITHUB_WORKSPACE/app
          image-name: app:${GITHUB_SHA}
